#include <QCoreApplication>

// This file is automatically generated by Qt
#include <myprojectadaptor.h>
// This is our DBUS implementation
#include <myproject_dbus.h>

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);

    // Qt automatically generated adaptor will take a pointer to an instance of the DBus implementation and forward
    // the calls to DBus.
    MyProjectDBus dbus{};
    MyProjectDBusAdaptor _{&dbus};

    return QCoreApplication::exec();
}
